apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-vm
spec:
  generators:
  # Only select external clusters, excludes local cluster
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{nameNormalized}}-demo-vm"
    spec:
      project: default
      source:
        repoURL: https://github.com/rmallam/RHSI-Hackathon.git
        targetRevision: HEAD
        path: "online-boutique/Annotations"
        kustomize:
          commonAnnotations:
            managed-cluster: "{{nameNormalized}}"
      destination:
        server: "{{server}}"
        namespace: skupper
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
